import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { useI18n } from "@/i18n";
import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { CalendarPlus, Pencil, RefreshCw, Sparkles, X } from "lucide-react";
import { toast } from "sonner";

const today = () => new Date().toISOString().slice(0, 10);
const PURPOSE_LABELS: Record<string, string> = { awareness: "認知", empathy: "顧客課題への共感", education: "教育", expertise: "専門性", case_study: "実績・事例", trust: "信頼", faq: "よくある質問", comparison: "比較・選び方", behind_scenes: "人柄・舞台裏", inquiry: "問い合わせ", sales: "販売" };
const parseWarnings = (value: string) => { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : []; } catch { return []; } };
export default function ContentStrategy() {
  const { t } = useI18n(); const utils = trpc.useUtils(); const strategiesQ = trpc.strategies.list.useQuery();
  const [startDate, setStartDate] = useState(today()); const [goal, setGoal] = useState(""); const [draftItemId, setDraftItemId] = useState<number | null>(null); const [drafts, setDrafts] = useState<Array<{ direction: string; content: string; difference: string }>>([]); const [selectedDraft, setSelectedDraft] = useState(""); const [selectedDraftIndex, setSelectedDraftIndex] = useState(0);
  const generate = trpc.strategies.generate.useMutation({ onSuccess: () => { utils.strategies.list.invalidate(); toast.success(t("7日間戦略を作成しました")); }, onError: e => toast.error(e.message) });
  const edit = trpc.strategies.editItem.useMutation({ onSuccess: () => utils.strategies.list.invalidate(), onError: e => toast.error(e.message) });
  const exclude = trpc.strategies.excludeItem.useMutation({ onSuccess: () => utils.strategies.list.invalidate(), onError: e => toast.error(e.message) });
  const ideas = trpc.strategies.draftIdeas.useMutation({ onSuccess: d => { setDrafts(d.drafts); setSelectedDraft(d.drafts[0]?.content ?? ""); setSelectedDraftIndex(0); }, onError: e => toast.error(e.message) });
  const schedule = trpc.strategies.addToCalendar.useMutation({ onSuccess: () => { toast.success(t("承認フローを維持してカレンダーへ追加しました")); setDraftItemId(null); utils.strategies.list.invalidate(); utils.posts.list.invalidate(); }, onError: e => toast.error(e.message) });
  const review = trpc.strategies.review.useMutation({ onSuccess: d => toast.success(d.review.summary), onError: e => toast.error(e.message) });
  const current = strategiesQ.data?.[0];
  return <div className="space-y-6">
    <PageHeader eyebrow="Plan" title={t("コンテンツ戦略")} description={t("選択中アカウントの実績とプロフィールから、次の7日間を計画します。投稿は自動公開されません。")} />
    <Card><CardContent className="p-4 flex flex-col sm:flex-row gap-3"><Input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="sm:w-44" aria-label={t("開始日")} /><Input value={goal} onChange={e => setGoal(e.target.value)} placeholder={t("今週の集客目標（任意）")} /><Button disabled={generate.isPending} onClick={() => generate.mutate({ startDate, goal: goal || undefined })}><Sparkles className="h-4 w-4 mr-1" />{generate.isPending ? t("作成中...") : current ? t("再生成") : t("7日間戦略を作成")}</Button></CardContent></Card>
    {!current ? <Card><CardContent className="py-12 text-center text-muted-foreground">{t("まだ戦略がありません。データ不足の場合は仮説として表示します。")}</CardContent></Card> : <>
      <Card><CardHeader><CardTitle>{current.goal}</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><p><span className="text-xs text-muted-foreground block">{t("対象期間")}</span>{current.startDate} – {current.items[6]?.date}</p><p><span className="text-xs text-muted-foreground block">{t("対象顧客")}</span>{current.audience}</p><p><span className="text-xs text-muted-foreground block">{t("中心メッセージ")}</span>{current.coreMessage}</p>{parseWarnings(current.warnings).map(warning => <p key={warning} className="text-xs text-amber-700">⚠ {warning}</p>)}</CardContent></Card>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{current.items.map(item => <Card key={item.id} className={item.status === "excluded" ? "opacity-50" : ""}><CardHeader className="pb-2"><div className="flex justify-between gap-2"><CardTitle className="text-base">{item.date} · {t(PURPOSE_LABELS[item.purpose] ?? item.purpose)}</CardTitle><span className="text-xs" aria-label={t("信頼度")}>{item.confidence}%</span></div></CardHeader><CardContent className="space-y-2 text-sm"><p className="font-semibold">{item.theme}</p><p>「{item.hook}」</p><p><span className="text-muted-foreground">CTA:</span> {item.cta || "—"}</p><dl className="grid grid-cols-[auto_1fr] gap-x-2 text-xs"><dt className="text-muted-foreground">{t("投稿形式")}</dt><dd>{item.format}</dd><dt className="text-muted-foreground">{t("推奨時刻")}</dt><dd>{item.recommendedTime}</dd><dt className="text-muted-foreground">{t("使用トレンド")}</dt><dd>{item.trend || "—"}</dd><dt className="text-muted-foreground">{t("期待する成果")}</dt><dd>{item.expectedOutcome || "—"}</dd></dl><p className="text-xs text-muted-foreground"><span className="font-medium">{t("根拠")}: </span>{item.rationale}</p>{item.hypothesis && <p className="text-xs text-amber-700">{t("データ不足を含む仮説です")}</p>}{item.factCheckWarning && <p className="text-xs text-destructive">⚠ {item.factCheckWarning}</p>}<div className="flex flex-wrap gap-1"><Button size="sm" onClick={() => { setDraftItemId(item.id); ideas.mutate({ itemId: item.id }); }} disabled={item.status === "excluded"}>{t("原稿を3案作成")}</Button><Button size="icon" variant="ghost" aria-label={t("編集")} onClick={() => { const theme = window.prompt(t("テーマを編集"), item.theme); if (theme) edit.mutate({ id: item.id, value: { theme } }); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label={t("除外")} onClick={() => exclude.mutate({ id: item.id })}><X className="h-4 w-4" /></Button></div></CardContent></Card>)}</div>
      <Button variant="outline" onClick={() => review.mutate({ strategyId: current.id })}><RefreshCw className="h-4 w-4 mr-1" />{t("週間振り返りを作成")}</Button>
    </>}
    <Dialog open={draftItemId !== null} onOpenChange={v => !v && setDraftItemId(null)}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{t("戦略から原稿を3案作成")}</DialogTitle></DialogHeader><div className="space-y-3">{ideas.isPending ? <p>{t("作成中...")}</p> : drafts.map((d, index) => <label key={d.direction} className="block border rounded-lg p-3"><input type="radio" name="draft" className="mr-2" checked={selectedDraftIndex === index} onChange={() => { setSelectedDraftIndex(index); setSelectedDraft(d.content); }} /><strong>{d.direction}</strong><p className="text-xs text-muted-foreground mt-1">{d.difference}</p><Textarea readOnly={selectedDraftIndex !== index} value={selectedDraftIndex === index ? selectedDraft : d.content} onChange={event => setSelectedDraft(event.target.value)} className="mt-2" /></label>)}</div><DialogFooter><Button variant="outline" onClick={() => setDraftItemId(null)}>{t("キャンセル")}</Button><Button disabled={!draftItemId || !selectedDraft} onClick={() => draftItemId && schedule.mutate({ itemId: draftItemId, content: selectedDraft })}><CalendarPlus className="h-4 w-4 mr-1" />{t("カレンダーへ追加")}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
